class EventTypes:

    ANALYSIS_REQUESTED = "ANALYSIS_REQUESTED"

    VALIDATION_COMPLETED = "VALIDATION_COMPLETED"
    VALIDATION_FAILED = "VALIDATION_FAILED"

    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"

    PERSISTENCE_COMPLETED = "PERSISTENCE_COMPLETED"